/** Seed data for the admin-managed Category reference table (SRS FR-C4.M2.11). Source: NIR Content.md */
export interface CategorySeed {
  slug: string;
  icon: string;
  nameEn: string;
  nameBn: string;
  descriptionEn: string;
  examplesEn: string;
}

export const CATEGORY_SEEDS: CategorySeed[] = [
  { slug: "agriculture-food-security", icon: "wheat", nameEn: "Agriculture & Food Security", nameBn: "কৃষি ও খাদ্য নিরাপত্তা", descriptionEn: "Smart agriculture, precision farming, fisheries, livestock, food processing, irrigation, and sustainable food production.", examplesEn: "Smart irrigation, AI crop monitoring, fisheries management, vertical farming" },
  { slug: "healthcare-medtech", icon: "heart-pulse", nameEn: "Healthcare & Medical Technology", nameBn: "স্বাস্থ্যসেবা ও চিকিৎসা প্রযুক্তি", descriptionEn: "Healthcare delivery, diagnostics, medical devices, telemedicine, pharmaceuticals, and public health.", examplesEn: "Telemedicine, portable diagnostic devices, AI disease detection" },
  { slug: "ict-digital-technology", icon: "cpu", nameEn: "ICT & Digital Technology", nameBn: "তথ্যপ্রযুক্তি ও ডিজিটাল প্রযুক্তি", descriptionEn: "AI, IoT, software, cybersecurity, blockchain, cloud computing, data analytics, and digital government services.", examplesEn: "AI applications, mobile apps, e-Governance, cybersecurity tools" },
  { slug: "education-skills", icon: "graduation-cap", nameEn: "Education & Skills Development", nameBn: "শিক্ষা ও দক্ষতা উন্নয়ন", descriptionEn: "E-learning platforms, research tools, digital classrooms, vocational training, and lifelong learning.", examplesEn: "Learning Management Systems, virtual classrooms, STEM education" },
  { slug: "environment-climate", icon: "leaf", nameEn: "Environment & Climate Change", nameBn: "পরিবেশ ও জলবায়ু পরিবর্তন", descriptionEn: "Environmental sustainability, climate resilience, biodiversity conservation, pollution control, waste management.", examplesEn: "Carbon monitoring, recycling technologies, climate adaptation" },
  { slug: "energy-renewables", icon: "sun", nameEn: "Energy & Renewable Energy", nameBn: "জ্বালানি ও নবায়নযোগ্য শক্তি", descriptionEn: "Renewable energy systems, solar technologies, energy efficiency, smart grids, battery technologies.", examplesEn: "Solar irrigation, biogas, smart energy management" },
  { slug: "industry-manufacturing", icon: "factory", nameEn: "Industry & Manufacturing", nameBn: "শিল্প ও উৎপাদন", descriptionEn: "Manufacturing technologies, industrial automation, robotics, production optimization, Industry 4.0.", examplesEn: "Smart factories, automation systems, industrial robotics" },
  { slug: "smart-cities-infrastructure", icon: "building-2", nameEn: "Smart Cities & Infrastructure", nameBn: "স্মার্ট নগর ও অবকাঠামো", descriptionEn: "Urban development, intelligent transportation, construction technology, water management, smart infrastructure.", examplesEn: "Smart traffic systems, GIS planning, intelligent buildings" },
  { slug: "transportation-logistics", icon: "truck", nameEn: "Transportation & Logistics", nameBn: "পরিবহন ও সরবরাহ ব্যবস্থা", descriptionEn: "Mobility solutions, logistics optimization, supply chain technologies, intelligent transport management.", examplesEn: "Fleet management, EV solutions, route optimization" },
  { slug: "fintech", icon: "landmark", nameEn: "Financial Technology (FinTech)", nameBn: "আর্থিক প্রযুক্তি", descriptionEn: "Digital financial services, payment systems, digital banking, financial inclusion, insurance technologies.", examplesEn: "Mobile banking, digital wallets, microfinance platforms" },
  { slug: "wash", icon: "droplets", nameEn: "Water, Sanitation & Hygiene (WASH)", nameBn: "পানি, স্যানিটেশন ও স্বাস্থ্যবিধি", descriptionEn: "Safe drinking water, sanitation, wastewater treatment, hygiene management, water conservation.", examplesEn: "Water purification, smart water monitoring, sanitation systems" },
  { slug: "disaster-resilience", icon: "shield-alert", nameEn: "Disaster Risk Reduction & Resilience", nameBn: "দুর্যোগ ঝুঁকি হ্রাস ও সহনশীলতা", descriptionEn: "Disaster preparedness, emergency response, early warning systems, climate resilience.", examplesEn: "Flood prediction, cyclone monitoring, emergency communication" },
  { slug: "governance-public-service", icon: "scale", nameEn: "Governance & Public Service Innovation", nameBn: "সুশাসন ও গণসেবা উদ্ভাবন", descriptionEn: "Digital public services, government process automation, civic technology, transparency, citizen engagement.", examplesEn: "Digital government services, smart public administration" },
  { slug: "science-research", icon: "flask-conical", nameEn: "Science, Research & Innovation", nameBn: "বিজ্ঞান, গবেষণা ও উদ্ভাবন", descriptionEn: "Scientific research, laboratory innovations, research commercialization, knowledge transfer.", examplesEn: "Research platforms, laboratory equipment, scientific discoveries" },
  { slug: "biotechnology-life-sciences", icon: "dna", nameEn: "Biotechnology & Life Sciences", nameBn: "জৈবপ্রযুক্তি ও জীববিজ্ঞান", descriptionEn: "Biotechnology, genetics, pharmaceuticals, biomedical engineering, life science innovations.", examplesEn: "Vaccine research, tissue engineering, biotech solutions" },
  { slug: "tourism-heritage", icon: "landmark-dome", nameEn: "Tourism & Cultural Heritage", nameBn: "পর্যটন ও সাংস্কৃতিক ঐতিহ্য", descriptionEn: "Tourism, cultural preservation, heritage digitization, creative industries.", examplesEn: "Digital tourism platforms, heritage preservation technologies" },
  { slug: "women-youth-empowerment", icon: "users", nameEn: "Women & Youth Empowerment", nameBn: "নারী ও যুব ক্ষমতায়ন", descriptionEn: "Entrepreneurship, employment, gender equality, youth development, social inclusion.", examplesEn: "Women's entrepreneurship, youth skill development platforms" },
  { slug: "social-innovation-community", icon: "handshake", nameEn: "Social Innovation & Community Development", nameBn: "সামাজিক উদ্ভাবন ও সম্প্রদায় উন্নয়ন", descriptionEn: "Community-driven innovations addressing social challenges, inclusion, poverty reduction.", examplesEn: "Community health, social enterprises, inclusive technologies" },
  { slug: "blue-economy", icon: "waves", nameEn: "Blue Economy & Marine Resources", nameBn: "ব্লু ইকোনমি ও সামুদ্রিক সম্পদ", descriptionEn: "Marine technologies, fisheries, coastal resource management, ocean conservation, maritime innovations.", examplesEn: "Marine monitoring, aquaculture technologies" },
  { slug: "emerging-technologies", icon: "sparkles", nameEn: "Emerging Technologies", nameBn: "উদীয়মান প্রযুক্তি", descriptionEn: "AI, quantum computing, drones, AR/VR, space technologies, nanotechnology, advanced robotics.", examplesEn: "AI, drones, robotics, digital twins, quantum research" },
];
